//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

var asns = []string{"AS4809", "AS9929", "AS58807"}

// knownPrefixes 是国内专用段兜底清单。
// 这些前缀只在国内 BGP 宣告，不向国际 BGP 宣告，RIPEstat 等国际采集源拿不到。
// 必须手工补齐，否则关键线路识别会漏。
var knownPrefixes = []entry{
	{"AS4809", "59.43.0.0/16"}, // CN2 GIA 骨干经典段
}

type ripeResp struct {
	Data struct {
		Prefixes []struct {
			Prefix string `json:"prefix"`
		} `json:"prefixes"`
	} `json:"data"`
}

type entry struct{ asn, cidr string }

func main() {
	client := &http.Client{Timeout: 30 * time.Second}

	var all []entry
	for _, asn := range asns {
		num := strings.TrimPrefix(asn, "AS")
		url := fmt.Sprintf("https://stat.ripe.net/data/announced-prefixes/data.json?resource=%s", num)

		rsp, err := client.Get(url)
		if err != nil {
			die("fetch %s: %v", asn, err)
		}
		var r ripeResp
		if err := json.NewDecoder(rsp.Body).Decode(&r); err != nil {
			rsp.Body.Close()
			die("decode %s: %v", asn, err)
		}
		rsp.Body.Close()

		kept := 0
		for _, p := range r.Data.Prefixes {
			_, cidr, err := net.ParseCIDR(p.Prefix)
			if err != nil {
				continue
			}
			if cidr.IP.To4() == nil {
				continue
			}
			all = append(all, entry{asn, cidr.String()})
			kept++
		}
		fmt.Printf("%s: %d total, %d IPv4 kept\n", asn, len(r.Data.Prefixes), kept)
	}

	for _, e := range knownPrefixes {
		all = append(all, e)
	}
	fmt.Printf("merged %d known prefixes\n", len(knownPrefixes))

	seen := map[string]bool{}
	uniq := all[:0]
	for _, e := range all {
		key := e.asn + " " + e.cidr
		if seen[key] {
			continue
		}
		seen[key] = true
		uniq = append(uniq, e)
	}
	sort.Slice(uniq, func(i, j int) bool {
		if uniq[i].asn != uniq[j].asn {
			return uniq[i].asn < uniq[j].asn
		}
		return uniq[i].cidr < uniq[j].cidr
	})

	var b strings.Builder
	b.WriteString("// Code generated by tools/genprefixes.go; DO NOT EDIT.\n")
	b.WriteString("// Run: go generate ./... to regenerate.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("var asnPrefixStrings = []struct {\n\tasn  string\n\tcidr string\n}{\n")
	for _, e := range uniq {
		fmt.Fprintf(&b, "\t{%q, %q},\n", e.asn, e.cidr)
	}
	b.WriteString("}\n")

	if err := os.WriteFile("prefixes_generated.go", []byte(b.String()), 0o644); err != nil {
		die("write file: %v", err)
	}
	fmt.Printf("wrote prefixes_generated.go (%d entries)\n", len(uniq))
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
